### PR TITLE
Upgrade package to TypeScript

### PR DESCRIPTION
**Pull request by webJose**
Doing the needful for a project that hasn't been updated for a while.

### CODE REVIEW

**Comment by webJose** [comment]
# Initial Chores

This first commit upgrades all packages to their latest versions.  There is a problem with `eslint` and `eslint-config-important-stuff`:  The latter is incompatible with eslint's new flat configuration format.  I suppose that someone more versed in `eslint` can figure this one out.  For now, the linting from husky's pre-commit action has been removed.

Unit testing is working.  The newer `jest` versions come without `jsdom`, so that has been added.  Also a few more configuration files have appeared for `jest` and `babel`.  I am no expert in either.  I did what I was told to by an SO answer I located.  Any expert is welcome to address any mistakes I made.

# Suggested Upgrade Roadmap

Ok, after studying the code and having in mind that the goal is to produce a TypeScript version, my suggestion is to:

1. Complete the chores of having up-to-date packages.
2. Re-writing the current logic in TypeScript.
3. Writing the new logic for Svelte v5.

The first part requires a smarter person than me.  Things like `babel` and `eslint` are not in my résumé.

One thing that I consider important is re-evaluate the need of all the packages that are currently installed, again, by someone more versed in this area than me.  Are there packages that have been superseded?  Are there newer, better options?  Should babel be removed?  For the last question, my opinion is **Yes**, because Svelte v5 will use rollup to transpile, bundle and minify as it will require a Svelte plug-in, and **the** plug-in, from what I read, is `rollup-plugin-svelte`.  So maybe moving to rollup now (in step 1) is desirable.

# Outlook for Step 3

As I'm about to finish a version of step 2, I believe that support for Svelte v5 should be separated from v4.  The typing is quite different, but more importantly, it is yet to be seen what options the new `mount()` function from Svelte v5 accepts.  Handling both versions of options in a single package is probably messy.

---

This is so far, my opinion on the matter.  Everyone, please don't be afraid to chip in.

**Comment by webJose** [comment]
@MilanKovacic, here's the draft PR for single-spa-svelte.

**Comment by webJose** [comment]
# Initial TypeScript Notes

As per usual, moving to TypeScript reveals many problems in the codebase, which of course is a good thing:  This is why we love TypeScript in the first place.

## Function singleSpaSvelte()

1. The default options have been removed.  It seems that they were only used to "calculate" the Svelte propperties for the constructor.  It's been replaced with the `nonSvelteOptionKeys` string array.
2. Thre is no merging of the given options with the default options because there are no default options anymore.
3. The `mountedInstances` object has been removed.  The instance is tracked with the `this` argument, which has been typed as an object with the `instance` property.
4. The `bootstrap()` function has been inlined in the return statement.
5. The lifecycle functions were given the suffix `Sspa` for clarity (they are not the "final" lifecycle functions).

### Notes

+ Even though not in the documentation, people could pass the Svelte constructor option `context` as part of the options parameter.  Should this be allowed?  If yes, we might as well type it and document it.

## Function mount()

1. It has been renamed to mountSspa.
2. No longer has the `mountedInstance` parameter.
3. The use of `Array.reduce` to calculate the Svelte properties has been replaced with a `for` loop as it has a simpler and more concise syntax.
4. Simplified the syntax around the returned promise:  Instead of `return Promise.resolve.then()`, the body synchronously does the job and then simply does `return Promise.resolve();` at the end.   Consequence:  The work is immediately done as opposed to being scheduled at the end of the browser's task pump.  Is this bad?  Is this a requirement for something?

### Notes

+ The link about creating a component has changed.  The source code has the updated link; documentation needs correction.
+ The construction of the `props` property with `Object.assign()` had me perplexed.  My conclusion is that the single-spa options that end up received in the `singleSpaProps` parameter of all lifecycle functions have the `customProps` object spreaded in them.  I made the SingleSpaProps reflect this with `[x: string]: any` but could be generically typed with `TProps`. Did not do it because I don't see an opportunity for end developers to take advantage of it.

## Function unmount()

1. TypeScript warns about the instance property possibly being null, so added a check in case the lifecycle function is called out of order.  Or should it silently exit?  The current implementation fails trying to access a property on `undefined`.  Or should I remove the guard to not impact performance?
2. In my opinion, `unmount()` needs to set the `instance` property back to null.
3. Simplified the syntax around the returned promise:  Instead of `return Promise.resolve.then()`, the body synchronously does the job and then simply does `return Promise.resolve();` at the end.   Consequence:  The work is immediately done as opposed to being scheduled at the end of the browser's task pump.  Is this bad?  Is this a requirement for something?

## Function update()

1. TypeScript warns about the instance property possibly being null, so added a check in case the lifecycle function is called out of order.  Or should it silently exit?  The current implementation fails trying to access a property on `undefined`.  Or should I remove the guard to not impact performance?
2. Simplified the syntax around the returned promise:  Instead of `return Promise.resolve.then()`, the body synchronously does the job and then simply does `return Promise.resolve();` at the end.   Consequence:  The work is immediately done as opposed to being scheduled at the end of the browser's task pump.  Is this bad?  Is this a requirement for something?

## Function chooseDomElementGetter()

I am pretty sure about my conclusion about customProps being spreaded.  Therefore, the line `props = props && props.customProps ? props.customProps : props;` always results in `props = props`.  With this in mind:

1. The check about the existence of `customProps` has been removed.
3. The single IF chain was split in separate IF's to simplify syntax.

## Function defaultDomElementGetter()

1. No changes, but I wonder where the possible `appName` property comes from.  Should it be added to the TS type?

### Notes

+ If `single-spa` had the default HTML ID convention packed in a function, the line `const htmlId = `single-spa-application:${appName}`;` could be replaced with `const htmlId = props.singleSpa.getDefaultMountId(appName);` and the naming convention could be centrally handled in the main `single-spa` library for every satellite package.

**Comment by internettrans** [comment]
Why was this closed? Migrating this package to typescript would be a good thing.

**Comment by webJose** [comment]
Hello.  I closed it because nothing moves.  I needed this upgrade to obtain a Svelte v5 version that I needed for work, and the inactivity was simply killing me.  Feel free to revive or copy any parts of this PR, or feel free to copy [@wjfe/single-spa-svelte](https://github.com/WJSoftware/wjfe-single-spa-svelte) which I made to fulfill my needs at work.

**Comment by internettrans** [comment]
I took a break but am back to maintaining single-spa this week, and hope to continue providing steady hours each week for the next few months.

Given the lack of funding, there should be no expectation of quick replies, reviews, or releases. If the open source community pays, I'll go back to zero-inbox GitHub queues, immediate bug fixes and publishes, etc.

**Comment by webJose** [comment]
I'm glad you took a break and made time for yourself.  Mental health is aways very important.

Having said that, being the owner of such a popular open-source project that has already risen suspicion about its abandonment, should have left someone in charge with enough power to take action on KTBR things or agreed-upon enhancements, such as this TypeScript enhancement, which I took under my wing to help me and also to help the community (as I could have done my own thing privately).  Anyway, just my opinion.  Feel free to disagree.

Even though I closed the PR, the changes are still detailed in this PR, and hopefully will help you spin this endeavor up again faster.

One last comment, if I may be so bold:  Holding `single-spa` ransom will probably backfire.  There is Qiankun that spun off from `single-spa`, and others can spin off to fill the void.  I'd hate to see `single-spa` go as I think it is the best micro-frontend solution in existence, but even I am thinking about a potential spin-off.

**Comment by internettrans** [comment]
> being the owner of such a popular open-source project that has already risen suspicion about its abandonment, should have left someone in charge

I donated thousands of unpaid hours to create single-spa and do not owe the open source community anything. I turned you down to join the core team and am not looking for your input on my governance of the project.

**Pull request closed without merging**
